name: Sword
version: '${version}'
main: btm.sword.Sword
api-version: '1.21.8'
loader: btm.sword.SwordPluginLoader

permissions:
  sword.use:
    description: Allows use of /sword command
    default: true
  sword.reload:
    description: Allows reloading configuration
    default: op
